config/routes.rb
Rails.application.routes.draw do
  devise_for :email_ids
  root 'home#index'
  get "/secret", to: "home#secret"

  get "/auth/:provider/callback", to: "sessions#create"
  post "/auth/:provider/callback", to: "sessions#create"

  resources :sessions
end

app/models/authenticate_user.rb
class AuthenticateUser

  include Virtus.model
  include ActiveModel::Model

  attribute :provider
  attribute :uid
  attribute :info, Hash
  attribute :credentials, Hash

  validates :provider, :uid, :info, presence: true

  # instantiate OmniauthSession with the controller env
  def self.build( omni_hash )
    self.new omni_hash.slice("provider", "uid", "info", "credentials")
  end

  def email
    info.fetch("email")
  end

  def save
    link_or_create_user
    authentication.save
  end

  def authentication
    @authentication ||= Authentication.
      where(attributes.slice(:provider, :uid)).first_or_initialize
  end

  def user
    @user ||= User.where(email: email).first_or_initialize
  end

private
  def link_or_create_user
    authentication.user || authentication.user = user
  end


end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/email_id.rb
class EmailId < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable


  alias uid id

  def info
    {name: email, email: email}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_signed_in?
    !!session[:user_id] or redirect_to root_path
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_email_id!, only: :secret
  before_action :user_signed_in?, only: :secret

  def index; end

  def secret; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    auth = AuthenticateUser.build( env["omniauth.auth"] )

    if auth.save
      session[:user_id] = auth.user.id

      redirect_to "/secret",
        notice: "yeyy got there with omniauth and #{params[:provider]} as provider !"
    else
      render text: "failed sorry try again"
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You got outa omni box"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.row
  %ul.col-md-6
    - EmailId.all.each do |email|
      %li
        = email.email
        ,
        = email.confirmed?
  .col-md-6
    = simple_form_for(SessionForm.new, url: "/auth/devise/callback") do |f|
      = f.error_notification
      .form-inputs
        = f.input :email, required: true, autofocus: true
        = f.input :password, required: true
      .form-actions
        = f.button :submit, "Connection"
    =# render "devise/shared/links"


%hr
%br
.row

  .col-md-6
    %h4 Devise classical Signup

    = link_to "signup", "/email_ids/sign_up"
    \|
    = link_to "signin", "/email_ids/sign_in"
    \|
    = link_to "logout", destroy_email_id_session_path, method: :delete

  .col-md-6
    %h4 Omniauth Signup

    = link_to "google", ""
    \|
    = link_to "signin", "/email_ids/sign_in"
    \|
    = link_to "logout", session_path(id: "current"), method: :delete

app/views/home/secret.html.haml
.row
  .col-md-12
    If you can see this page you are logged in !

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "Omnidevisable"
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

  %body
    %header.navbar.navbar-inverse(role="banner")
      .container
        .navbar-header
          = link_to "Home", "/", class: 'navbar-brand'
        .navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "secret page", "/secret"

    .container
      - flash.each do |name, msg|
        .row
          .col-md-6.col-md-offset-3
            = content_tag :div, msg, class: "alert alert-info text-center"

      = yield

    %footer(style="height:60px")
      .container
        %hr
        .row
          .text-center=link_to "on github", "https://github.com/charly"

    = javascript_include_tag "application"